name: 'Publish Unit Test Results'
author: 'EnricoMi'
description: 'A GitHub Action that publishes unit test results on GitHub'
inputs:
  github_token:
    description: 'GitHub API Access Token'
    required: true
  commit:
    description: 'Commit SHA to which test results are published. Only needed if the value of GITHUB_SHA does not work for you.'
    required: false
  check_name:
    description: 'Name of the created check run'
    required: false
    default: 'Unit Test Results'
  comment_title:
    description: 'Title of PR comments, defaults to value of check_name input'
    required: false
  files:
    description: 'File pattern of test result files'
    required: true
  report_individual_runs:
    description: 'Individual runs of the same test may see different failures. Reports all individual failures when set "true" or the first only otherwise'
    required: false
  deduplicate_classes_by_file_name:
    description: 'De-duplicates classes with same name by their file name when set "true", combines test results for those classes otherwise'
    required: false
  hide_comments:
    description: 'Configures which earlier comments of the action to hide: off - no comments, orphaned commits - comments for commits that are removed from the branch, all but latest - all comments but the latest'
    required: false
    default: 'all but latest'
  comment_on_pr:
    description: 'Control PR comments: false - disable PR comments, true - comment on PRs'
    required: false
    default: 'true'
  comment_test_changes:
    description: 'Configure which test changes are reported in PR comments (comma-separated list): added, removed, skipped, un-skipped, none'
    required: false
    default: 'removed, skipped'
  comment_test_changes_limit:
    description: 'Limits the number of added / removed / skipped / un-skipped tests listed on PR comments. The default is 5.'
    required: false
  check_run_annotations:
    description: 'Adds additional information to the check run (comma-separated list): all tests - list all found tests, skipped tests - list all skipped tests, none - no extra annotations at all'
    required: false
    default: 'all tests, skipped tests'
  check_run_annotations_branch:
    description: 'Adds check run annotations only on given branches. If not given, this defaults to the default branch of your repository, e.g. main or master. Comma separated list of branch names allowed, asterisk "*" matches all branches.'
    required: false
  log_level:
    description: 'Action logging level'
    required: false
    default: 'INFO'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'green'
