name: 'Publish Test Results'
author: 'EnricoMi'
description: 'A GitHub Action that publishes JUnit, NUnit, XUnit, and TRX test results on GitHub'

inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: false
  github_retries:
    description: 'Requests to the GitHub API are retried this number of times. The value must be a positive integer or zero.'
    default: '10'
    required: false
  commit:
    description: 'Commit SHA to which test results are published. Only needed if the value of GITHUB_SHA does not work for you.'
    required: false
  check_name:
    description: 'Name of the created check run'
    default: 'Test Results'
    required: false
  comment_title:
    description: 'An alternative title for the pull request comment. Defaults to value of check_name input'
    required: false
  comment_mode:
    description: 'The action posts comments to pull requests that are associated with the commit. Set to "always" - always comment, "changes" - comment when changes w.r.t. the target branch exist, "changes in failures" - when changes in the number of failures and errors exist, "changes in errors" - when changes in the number of (only) errors exist, "failures" - when failures or errors exist, "errors" - when (only) errors exist, "off" - to not create pull request comments'
    default: 'always'
    required: false
  fail_on:
    description: 'The created test result check run has failure state if any test fails or test errors occur. Never fails when set to "nothing", fails only on errors when set to "errors". Default is "test failures".'
    default: 'test failures'
    required: false
  action_fail:
    description: 'When set "true", the action itself fails when tests have failed (see option fail_on).'
    default: 'false'
    required: false
  action_fail_on_inconclusive:
    description: 'When set "true", the action itself fails when tests are inconclusive (no test results).'
    default: 'false'
    required: false
  files:
    description: 'Deprecated, use "junit_files" instead.'
    required: false
  junit_files:
    description: 'File patterns of JUnit XML test result files. Supports *, **, ?, and []. Use multiline string for multiple patterns. Patterns starting with ! exclude the matching files. There have to be at least one pattern starting without a `!`.'
    required: false
  nunit_files:
    description: 'File patterns of NUnit XML test result files. Supports *, **, ?, and []. Use multiline string for multiple patterns. Patterns starting with ! exclude the matching files. There have to be at least one pattern starting without a `!`.'
    required: false
  xunit_files:
    description: 'File patterns of XUnit XML test result files. Supports *, **, ?, and []. Use multiline string for multiple patterns. Patterns starting with ! exclude the matching files. There have to be at least one pattern starting without a `!`.'
    required: false
  trx_files:
    description: 'File patterns of TRX test result files. Supports *, **, ?, and []. Use multiline string for multiple patterns. Patterns starting with ! exclude the matching files. There have to be at least one pattern starting without a `!`.'
    required: false
  time_unit:
    description: 'Time values in the test result files have this unit. Supports "seconds" and "milliseconds".'
    default: 'seconds'
    required: false
  report_individual_runs:
    description: 'Individual runs of the same test may see different failures. Reports all individual failures when set "true" or the first only otherwise'
    required: false
  deduplicate_classes_by_file_name:
    description: 'De-duplicates classes with same name by their file name when set "true", combines test results for those classes otherwise'
    required: false
  ignore_runs:
    description: 'Does not collect test run information from the test result files, which is useful for very large files. This disables any check run annotations'
    default: 'false'
    required: false
  job_summary:
    description: 'Set to "true", the results are published as part of the job summary page of the workflow run'
    default: 'true'
    required: false
  compare_to_earlier_commit:
    description: 'Test results are compared to results of earlier commits to highlight changes: "false" - disable comparison, "true" - compare across commits'
    default: 'true'
    required: false
  pull_request_build:
    description: 'As part of pull requests, GitHub builds a merge commit, which combines the commit and the target branch. If tests ran on the actual pushed commit, then set this to "commit". Defaults to "merge".'
    default: 'merge'
    required: false
  event_file:
    description: 'An alternative event file to use. Useful to replace a "workflow_run" event file with the actual source event file.'
    required: false
  event_name:
    description: 'An alternative event name to use. Useful to replace a "workflow_run" event name with the actual source event name: github.event.workflow_run.event.'
    required: false
  test_changes_limit:
    description: 'Limits the number of removed or skipped tests reported on pull request comments. This report can be disabled with a value of 0. The default is 10.'
    required: false
  check_run_annotations:
    description: 'Adds additional information to the check run. This is a comma-separated list of any of the following values: "all tests" - list all found tests, "skipped tests" - list all skipped tests. Set to "none" to add no extra annotations at all'
    default: 'all tests, skipped tests'
    required: false
  check_run_annotations_branch:
    description: 'Adds check run annotations only on given branches. Comma-separated list of branch names allowed, asterisk "*" matches all branches. Defaults to event.repository.default_branch or "main, master".'
    required: false
  seconds_between_github_reads:
    description: 'Sets the number of seconds the action waits between concurrent read requests to the GitHub API. This throttles the API usage to avoid abuse rate limits: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits'
    default: '0.25'
    required: false
  seconds_between_github_writes:
    description: 'Sets the number of seconds the action waits between concurrent write requests to the GitHub API. This throttles the API usage to avoid abuse rate limits: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits'
    default: '2.0'
    required: false
  json_file:
    description: 'Results are written to this JSON file.'
    required: false
  json_thousands_separator:
    description: 'Formatted numbers in JSON use this character to separate groups of thousands. Common values are "," or ".". Defaults to punctuation space (\u2008).'
    default: ' '
    required: false
  json_test_case_results:
    description: 'Write out all individual test case results to the JSON file. Setting this to "true" can greatly increase the size of the output. Defaults to "false".'
    default: false
    required: false

outputs:
  json:
    description: "Test results as JSON"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/enricomi/publish-unit-test-result-action:v2.2.0'

branding:
  icon: 'check-circle'
  color: 'green'
