name: 'Publish Unit Test Results'
author: 'EnricoMi'
description: 'A GitHub Action that publishes unit test results on GitHub'
inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: false
  github_retries:
    description: 'Requests to the GitHub API are retried this number of times. The value must be a positive integer or zero.'
    default: '10'
    required: false
  commit:
    description: 'Commit SHA to which test results are published. Only needed if the value of GITHUB_SHA does not work for you.'
    required: false
  check_name:
    description: 'Name of the created check run'
    default: 'Unit Test Results'
    required: false
  comment_title:
    description: 'Title of PR comments, defaults to value of check_name input'
    required: false
  fail_on:
    description: 'The created test result check run has failure state if any test fails or test errors occur. Never fails when set to "nothing", fails only on errors when set to "errors". Default is "test failures".'
    default: 'test failures'
    required: false
  files:
    description: 'File patterns of test result files. Supports *, **, ?, and []. Use multiline string for multiple patterns.'
    required: true
  report_individual_runs:
    description: 'Individual runs of the same test may see different failures. Reports all individual failures when set "true" or the first only otherwise'
    required: false
  deduplicate_classes_by_file_name:
    description: 'De-duplicates classes with same name by their file name when set "true", combines test results for those classes otherwise'
    required: false
  hide_comments:
    description: 'Configures which earlier comments of the action to hide: off - no comments, orphaned commits - comments for commits that are removed from the branch, all but latest - all comments but the latest'
    default: 'all but latest'
    required: false
  comment_on_pr:
    description: 'Deprecated, please use comment_mode instead!'
    required: false
  comment_mode:
    description: 'Control PR comments: off - disable PR comments, create new - create comments on PRs, each time a new one, update last - create comment on PR, reuse an existing one'
    default: 'update last'
    required: false
  compare_to_earlier_commit:
    description: 'Test results are compared to results of earlier commits to highlight changes: false - disable comparison, true - compare across commits'
    default: 'true'
    required: false
  pull_request_build:
    description: 'Pull request events build a merge of the branch and the target branch, not just the commit that has been pushed. When your workflow deviates from this behaviour and builds the actual commit, then set this option to "commit". Defaults to "merge".'
    default: 'merge'
    required: false
  event_file:
    description: 'An alternative event file to use. Useful to replace a "workflow_run" event file with the actual source event file.'
    required: false
  event_name:
    description: 'An alternative event name to use. Useful to replace a "workflow_run" event name with the actual source event name: github.event.workflow_run.event.'
    required: false
  test_changes_limit:
    description: 'Limits the number of removed or skipped tests listed on PR comments. This can be disabled with a value of 0. The default is 10.'
    required: false
  check_run_annotations:
    description: 'Adds additional information to the check run (comma-separated list): all tests - list all found tests, skipped tests - list all skipped tests, none - no extra annotations at all'
    default: 'all tests, skipped tests'
    required: false
  check_run_annotations_branch:
    description: 'Adds check run annotations only on given branches. If not given, this defaults to the default branch of your repository, e.g. main or master. Comma separated list of branch names allowed, asterisk "*" matches all branches.'
    required: false
  seconds_between_github_reads:
    description: 'Sets the number of seconds the action waits between concurrent read requests to the GitHub API. This throttles the API usage to avoid abuse rate limits: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits'
    default: '0.25'
    required: false
  seconds_between_github_writes:
    description: 'Sets the number of seconds the action waits between concurrent write requests to the GitHub API. This throttles the API usage to avoid abuse rate limits: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits'
    default: '2.0'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.23'
branding:
  icon: 'check-circle'
  color: 'green'
