name: 'Fetch workflows'
author: 'im-open'
description: 'A GitHub Action to find workflows matching a query'

outputs:
  total_workflows:
    description: 'Total number of workflows using this action'
    value: ${{ steps.workflows.outputs.total }}

runs:
  using: 'composite'
  steps:
    - name: Fetch workflows
      id: workflows
      shell: bash
      run: |
        for i in {1..60}
        do
          workflows=$(curl -s https://github.com/im-open/publish-unit-test-result-action | (grep "Used by" || true) | sed -e "s/.*title=//" -e 's/["]//g' | cut -d " " -f 1)
          if [ -n "$workflows" ]
          then
            echo "total=$workflows" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Attempt $i failed"
          sleep 60
        done
        echo "Giving up"
        exit 1

branding:
  icon: 'download-cloud'
  color: 'green'
