name: Deploy to GitHub Container Registry

on:
  push:

jobs:
  deploy:
    name: Deploy to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
          add_git_labels: true
          always_pull: true
          push: true
